import type { Metadata } from "next";
import { Marcellus, Syne } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/util/lenis";

const marcellus = Marcellus({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-marcellus",
});

const syne = Syne({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
    variable: "--font-syne",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* <ReactLenis root> */}
            <body className={`${marcellus.variable} ${syne.variable} antialiased`}>{children}</body>
            {/* </ReactLenis> */}
        </html>
    );
}
